namespace BreadboxF

type Vic2Configuration(hBlankSet:int, hBlankClear:int, vBlankSet:int, vBlankClear:int, cyclesPerRasterLine:int, rasterLinesPerFrame:int) =
    member val CyclesPerRasterLine = cyclesPerRasterLine
    member val HBlankSet = hBlankSet
    member val HBlankClear = hBlankClear
    member val VBlankSet = vBlankSet
    member val VBlankClear = vBlankClear
    member val RasterLinesPerFrame = rasterLinesPerFrame

type Vic2State() = 
    let mobX = [|0;0;0;0;0;0;0;0|]
    let mobY = [|0;0;0;0;0;0;0;0|]
    let mutable rasterY = 0
    let mutable extraColorMode = false
    let mutable bitmapMode = false
    let mutable displayEnabled = false
    let mutable rowSelect = false
    let mutable yScroll = 0
    let mutable lightPenX = 0
    let mutable lightPenY = 0
    let mobEnabled = [|false;false;false;false;false;false;false;false|]
    let mutable res = false
    let mutable multiColorMode = false
    let mutable columnSelect = false
    let mutable xScroll = 0
    let mobYExpansionEnabled = [|false;false;false;false;false;false;false;false|]
    let mobYExpansionToggle = [|false;false;false;false;false;false;false;false|]
    let mutable videoMemoryPointer = 0
    let mutable characterBankPointer = 0
    let mutable irq = false
    let mutable lightPenIrq = false
    let mutable mobMobCollisionIrq = false
    let mutable mobBackgroundCollisionIrq = false
    let mutable rasterIrq = false
    let mutable lightPenIrqEnabled = false
    let mutable mobMobCollisionIrqEnabled = false
    let mutable mobBackgroundCollisionIrqEnabled = false
    let mutable rasterIrqEnabled = false
    let mobDataPriority = [|false;false;false;false;false;false;false;false|]
    let mobMultiColorEnabled = [|false;false;false;false;false;false;false;false|]
    let mobMultiColorToggle = [|false;false;false;false;false;false;false;false|]
    let mobXExpansionEnabled = [|false;false;false;false;false;false;false;false|]
    let mobXExpansionToggle = [|false;false;false;false;false;false;false;false|]
    let mobMobCollision = [|false;false;false;false;false;false;false;false|]
    let mobDataCollision = [|false;false;false;false;false;false;false;false|]
    let mutable borderColor = 0
    let backgroundColor = [|0;0;0;0|]
    let mobMultiColor = [|0;0|]
    let mobColor = [|0;0;0;0;0;0;0;0|]
    let mutable rasterX = 0
    let mutable vBlank = true
    let mutable hBlank = true
